from random import randint
nome =  input ('Digite o nome do cliente: ')
telefone = input ('Digite o telefone do cliente: ')
endereco = input ('Digite o endereço do cliente: ')
venda = float(input('Digite o valor da venda: '))
fim_exp = [nome, telefone, endereco, venda]
sorteio = randint('{nome}' + '{telefone}' + '{endereco}' + '{venda}')
lista = [nome , telefone , endereco , venda]
while 

print(sorteio)